# otel-collector-config.yaml 
receivers:
  otlp/ingest:              
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319

  otlp/postrouter:           
    protocols:
      grpc:
        endpoint: 0.0.0.0:4320

processors:
  transform/to_sigma:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          # - 'set(attributes["Image"], attributes["proc.name"])'
          # - 'set(attributes["TargetFilename"], attributes["fd.name"]) where attributes["fd.name"] != nil'
          # - 'set(attributes["TargetFilename"], attributes["evt.arg.filename"]) where attributes["evt.arg.filename"] != nil'
          # - 'set(attributes["proc.name"], "wget") where attributes["proc.name"] == nil and IsMatch(attributes["proc.cmdline"], "^wget\\s")'
          - 'set(attributes["Image"], attributes["Image"])'
          - 'set(attributes["Image"], attributes["OriginalFileName"]) where attributes["Image"] == nil and attributes["OriginalFileName"] != nil'
          - 'set(attributes["TargetFilename"], attributes["TargetFilename"]) where attributes["TargetFilename"] != nil'
          - 'set(attributes["TargetFilename"], attributes["FileName"]) where attributes["TargetFilename"] == nil and attributes["FileName"] != nil'
          - 'set(attributes["TargetFilename"], attributes["FilePath"]) where attributes["TargetFilename"] == nil and attributes["FilePath"] != nil'
          - 'set(attributes["parentSpanID"], span.parent_span_id) where IsRootSpan() == false'

  # ★ sigma.alert 태그가 달린 트레이스만 KEEP, 그 외는 DROP
  tail_sampling/alerts:
    decision_wait: 5s         
    policies:
      - name: keep_sigma
        type: string_attribute
        string_attribute:
          key: sigma.alert
          values: [".+"]      
          enabled_regex_matching: true

  batch:
    timeout: 200ms

exporters:
  otlp/sigma:
    endpoint: "localhost:55680"
    tls: { insecure: true }
    compression: none

  otlphttp/jaeger:
    endpoint: "http://localhost:4318"
    tls: { insecure: true }

  file/all_events:
    path: ./event/events.jsonl
    format: json

  debug:
    verbosity: detailed

service:
  pipelines:
    traces/ingest:              # 1차 파이프라인 
      receivers:  [otlp/ingest]
      processors: [transform/to_sigma, batch]
      exporters:  [otlp/sigma]

    traces/final:               # 2차 파이프라인 
      receivers:  [otlp/postrouter]
      processors: [tail_sampling/alerts, batch] 
      exporters:  [otlphttp/jaeger, file/all_events, debug]

  telemetry:
    logs:
      level: debug
